### ISSUE TITLE
Please create a tag

### ISSUE THREAD

**Issue by amstan** [LMBernardo/mjpg-streamer#2]
So that `git describe --long --tags` works.

I see that you're also an [Arch fan](https://aur.archlinux.org/packages/mjpg-streamer-git#comment-880374), but if i try to edit the PKGBUILD with your repo it'll fail the building due to the `pkgver()` code, that could easily be fixed by you adding a tag in this repo. At least make it match the [upstream's tag](https://github.com/jacksonliam/mjpg-streamer/tree/v1.0.0) so version numbers are portable, or perhaps make a new namespace.

**Comment by FabioLolix** [comment]
+1 for pushing the tag

> with your repo it'll fail the building due to the check() code

in the pkgbuild there isn't a check() function, it is the pkgver() function that fails if there aren't git tag

which you can change to from "git describe ..." to
>   printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"

Incrementing epoch to 2 is also necessary if you update your pkgbuild with AUR helpers

https://wiki.archlinux.org/title/VCS_package_guidelines#Git

**Comment by LMBernardo** [comment]
I've added a tag with a minor version bump. If this works now, let me know and I will close this issue.

Thanks for reporting!

**Comment by FabioLolix** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=mjpg-streamer-git&id=df78e20d7024bfe16210ad489fd80624466bb5b0

https://aur.archlinux.org/cgit/aur.git/commit/?h=mjpg-streamer&id=b81fb95d01098a21d336fcb006701bae14031fe7

The issue can be closed
